"""Add transaction analytics fields

Revision ID: 3b704e50e3b1
Revises: 
Create Date: 2026-03-02 23:13:25.896020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b704e50e3b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'plaid_account_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_bank_accounts_plaid_account_id'), 'bank_accounts', type_='unique')
    op.drop_index(op.f('ix_bank_accounts_plaid_account_id'), table_name='bank_accounts')
    op.create_index(op.f('ix_bank_accounts_plaid_account_id'), 'bank_accounts', ['plaid_account_id'], unique=True)
    op.add_column('transactions', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('transactions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('merchant_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'pending')
    op.drop_column('transactions', 'merchant_name')
    op.drop_column('transactions', 'category')
    op.drop_column('transactions', 'date')
    op.drop_index(op.f('ix_bank_accounts_plaid_account_id'), table_name='bank_accounts')
    op.create_index(op.f('ix_bank_accounts_plaid_account_id'), 'bank_accounts', ['plaid_account_id'], unique=False)
    op.create_unique_constraint(op.f('uq_bank_accounts_plaid_account_id'), 'bank_accounts', ['plaid_account_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('bank_accounts', 'plaid_account_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
