"""update to dashboard logic, assets, libabilites

Revision ID: cb5f48db8d2d
Revises: c237aab5de28
Create Date: 2026-03-06 13:44:58.368437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5f48db8d2d'
down_revision: Union[str, Sequence[str], None] = 'c237aab5de28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
